version: '3.5'

services:
  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      #MARIADB_USER: root
      #MARIADB_PASSWORD: root
      MARIADB_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - "./dbData:/var/lib/mysql"
      - ./app/db.sql:/docker-entrypoint-initdb.d/db.sql
  
  web:
    container_name: web
    build: .
    depends_on:
      - mariadb
    environment:
      DB_HOSTNAME: mariadb
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: store
      DB_CHARSET: utf8mb4
      MAIL_ADDRESS: "securebook760@gmail.com"
      MAIL_PASSWORD: "gpuu eymu xxzy cgte"
    ports:
      - 80:80
      - 443:443 # for ssl traffic
    volumes:
      - ./app:/var/www/securebs
  #web:
  #  build: .
  #  ports:
  #    - "8443:443"
  #  volumes:
  #    - ./app:/var/www/html/
  #    #- ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
  #    #- ./certs:/etc/nginx/ssl
  #  depends_on:
  #    - php
#
  #php:
  #  image: php:8.1-fpm
  #  expose:
  #    - 9000
  #  volumes:
  #    - ./app:/var/www/html