services:
  mariadb:
    container_name: mariadb
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: store
    ports:
      - "3306:3306"
    volumes:
      - "./dbData:/var/lib/mysql"
      - ./app/db.sql:/docker-entrypoint-initdb.d/db.sql
  
  web:
    container_name: web
    build: .
    depends_on:
      - mariadb
    environment:
      DB_HOSTNAME: mariadb
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: store
      DB_CHARSET: utf8mb4
      MAIL_ADDRESS: "securebook760@gmail.com"
      MAIL_PASSWORD: "gpuu eymu xxzy cgte"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/securebs
      - "./app.htaccess:/var/www/html/.htaccess"